/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alert = IDL.Record({
  'message' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const Status = IDL.Variant({
  'found' : IDL.Null,
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'underReview' : IDL.Null,
});
export const ChildRecord = IDL.Record({
  'age' : IDL.Nat,
  'status' : Status,
  'lastSeenPlace' : IDL.Text,
  'lastLocation' : IDL.Text,
  'name' : IDL.Text,
  'contactNumber' : IDL.Text,
  'photoId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalCases' : IDL.Nat,
  'activeCases' : IDL.Nat,
  'foundCases' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlert' : IDL.Func([IDL.Tuple(IDL.Text, IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdminRole' : IDL.Func([IDL.Text], [], []),
  'deleteCase' : IDL.Func([IDL.Text], [], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllCases' : IDL.Func([], [IDL.Vec(ChildRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([IDL.Text], [ChildRecord], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCase' : IDL.Func([ChildRecord], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCaseStatus' : IDL.Func([IDL.Tuple(IDL.Text, Status)], [], []),
  'updateStatusToFound' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alert = IDL.Record({
    'message' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const Status = IDL.Variant({
    'found' : IDL.Null,
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'underReview' : IDL.Null,
  });
  const ChildRecord = IDL.Record({
    'age' : IDL.Nat,
    'status' : Status,
    'lastSeenPlace' : IDL.Text,
    'lastLocation' : IDL.Text,
    'name' : IDL.Text,
    'contactNumber' : IDL.Text,
    'photoId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalCases' : IDL.Nat,
    'activeCases' : IDL.Nat,
    'foundCases' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlert' : IDL.Func([IDL.Tuple(IDL.Text, IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdminRole' : IDL.Func([IDL.Text], [], []),
    'deleteCase' : IDL.Func([IDL.Text], [], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllCases' : IDL.Func([], [IDL.Vec(ChildRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([IDL.Text], [ChildRecord], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCase' : IDL.Func([ChildRecord], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCaseStatus' : IDL.Func([IDL.Tuple(IDL.Text, Status)], [], []),
    'updateStatusToFound' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };